[2025-04-01T16:16:46.701-0500] {processor.py:186} INFO - Started process (PID=4084) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:16:46.702-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:16:46.705-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:16:46.704-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:16:46.726-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:16:46.722-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:16:46.728-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:16:46.727-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:16:46.729-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:16:46.743-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-04-01T16:18:43.317-0500] {processor.py:186} INFO - Started process (PID=4155) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:18:43.318-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:18:43.320-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:18:43.319-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:18:43.342-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:18:43.337-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:18:43.343-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:18:43.343-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:18:43.344-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:18:43.359-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-04-01T16:20:12.110-0500] {processor.py:186} INFO - Started process (PID=4227) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:20:12.111-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:20:12.113-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:20:12.112-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:20:12.133-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:20:12.129-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:20:12.134-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:20:12.134-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:20:12.135-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:20:12.148-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:21:41.259-0500] {processor.py:186} INFO - Started process (PID=4300) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:21:41.260-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:21:41.262-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:21:41.262-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:21:41.282-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:21:41.278-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:21:41.284-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:21:41.283-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:21:41.284-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:21:41.297-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:23:03.552-0500] {processor.py:186} INFO - Started process (PID=4366) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:23:03.553-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:23:03.555-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:23:03.555-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:23:03.575-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:23:03.571-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:23:03.577-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:23:03.576-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:23:03.578-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:23:03.591-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:24:38.510-0500] {processor.py:186} INFO - Started process (PID=4438) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:24:38.511-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:24:38.513-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:24:38.512-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:24:38.533-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:24:38.529-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:24:38.534-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:24:38.534-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:24:38.535-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:24:38.548-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:26:13.008-0500] {processor.py:186} INFO - Started process (PID=4509) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:26:13.010-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:26:13.012-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:26:13.011-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:26:13.033-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:26:13.028-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:26:13.035-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:26:13.034-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:26:13.036-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:26:13.049-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-04-01T16:27:45.251-0500] {processor.py:186} INFO - Started process (PID=4580) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:27:45.253-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:27:45.255-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:27:45.254-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:27:45.275-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:27:45.271-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:27:45.276-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:27:45.276-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:27:45.277-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:27:45.290-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:29:14.881-0500] {processor.py:186} INFO - Started process (PID=4650) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:29:14.882-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:29:14.884-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:29:14.883-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:29:14.904-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:29:14.900-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:29:14.906-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:29:14.905-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:29:14.906-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:29:14.919-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:30:45.823-0500] {processor.py:186} INFO - Started process (PID=4722) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:30:45.824-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:30:45.826-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:30:45.825-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:30:45.846-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:30:45.842-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:30:45.848-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:30:45.847-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:30:45.849-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:30:45.862-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:32:23.473-0500] {processor.py:186} INFO - Started process (PID=4795) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:32:23.474-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:32:23.477-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:32:23.476-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:32:23.498-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:32:23.494-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:32:23.500-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:32:23.499-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:32:23.500-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:32:23.514-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-04-01T16:33:54.964-0500] {processor.py:186} INFO - Started process (PID=4865) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:33:54.965-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:33:54.967-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:33:54.966-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:33:54.987-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:33:54.983-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:33:54.989-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:33:54.988-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:33:54.989-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:33:55.003-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:35:19.328-0500] {processor.py:186} INFO - Started process (PID=4934) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:35:19.329-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:35:19.332-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:35:19.331-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:35:19.351-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:35:19.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:35:19.353-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:35:19.352-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:35:19.354-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:35:19.367-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:36:56.256-0500] {processor.py:186} INFO - Started process (PID=5005) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:36:56.257-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:36:56.259-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:36:56.258-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:36:56.279-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:36:56.275-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:36:56.280-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:36:56.280-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:36:56.281-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:36:56.294-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:38:28.099-0500] {processor.py:186} INFO - Started process (PID=5074) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:38:28.100-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:38:28.102-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:38:28.102-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:38:28.124-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:38:28.119-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:38:28.125-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:38:28.124-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:38:28.126-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:38:28.139-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-04-01T16:39:57.723-0500] {processor.py:186} INFO - Started process (PID=5145) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:39:57.724-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:39:57.726-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:39:57.726-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:39:57.747-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:39:57.742-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:39:57.748-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:39:57.747-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:39:57.749-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:39:57.762-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:41:37.360-0500] {processor.py:186} INFO - Started process (PID=5219) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:41:37.361-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:41:37.363-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:41:37.362-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:41:37.384-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:41:37.379-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:41:37.385-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:41:37.384-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:41:37.386-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:41:37.399-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:43:10.035-0500] {processor.py:186} INFO - Started process (PID=5289) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:43:10.036-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:43:10.038-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:43:10.037-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:43:10.058-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:43:10.054-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:43:10.059-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:43:10.059-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:43:10.060-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:43:10.073-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:44:42.621-0500] {processor.py:186} INFO - Started process (PID=5360) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:44:42.622-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:44:42.624-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:44:42.624-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:44:42.645-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:44:42.640-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:44:42.646-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:44:42.645-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:44:42.647-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:44:42.660-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:46:21.115-0500] {processor.py:186} INFO - Started process (PID=5433) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:46:21.116-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:46:21.118-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:46:21.117-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:46:21.138-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:46:21.133-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:46:21.139-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:46:21.139-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:46:21.140-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:46:21.153-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T16:47:58.177-0500] {processor.py:186} INFO - Started process (PID=5505) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:47:58.178-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:47:58.180-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:47:58.179-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:47:58.201-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:47:58.196-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:47:58.202-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:47:58.202-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:47:58.203-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:47:58.217-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-04-01T16:49:28.360-0500] {processor.py:186} INFO - Started process (PID=5574) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:49:28.361-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:49:28.363-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:49:28.362-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:49:28.383-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:49:28.378-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:49:28.384-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:49:28.383-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:49:28.385-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:49:28.397-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-04-01T16:50:55.388-0500] {processor.py:186} INFO - Started process (PID=5643) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:50:55.389-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:50:55.391-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:50:55.390-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:50:55.410-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:50:55.406-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:50:55.412-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:50:55.411-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:50:55.413-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:50:55.425-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-04-01T16:52:38.843-0500] {processor.py:186} INFO - Started process (PID=5717) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:52:38.844-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:52:38.847-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:52:38.846-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:52:38.868-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:52:38.864-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:52:38.870-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:52:38.869-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:52:38.870-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:52:38.884-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-04-01T16:54:13.766-0500] {processor.py:186} INFO - Started process (PID=5789) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:54:13.767-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:54:13.769-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:54:13.768-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:54:13.790-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:54:13.786-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:54:13.791-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:54:13.791-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:54:13.792-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:54:13.805-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:55:45.923-0500] {processor.py:186} INFO - Started process (PID=5860) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:55:45.924-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:55:45.926-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:55:45.926-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:55:45.947-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:55:45.942-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:55:45.948-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:55:45.948-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:55:45.949-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:55:45.962-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:57:20.021-0500] {processor.py:186} INFO - Started process (PID=5932) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:57:20.022-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:57:20.024-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:57:20.024-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:57:20.044-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:57:20.040-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:57:20.046-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:57:20.045-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:57:20.046-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:57:20.060-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T16:58:54.299-0500] {processor.py:186} INFO - Started process (PID=6002) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:58:54.300-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T16:58:54.302-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:58:54.301-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:58:54.322-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:58:54.317-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T16:58:54.323-0500] {logging_mixin.py:190} INFO - [2025-04-01T16:58:54.323-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T16:58:54.324-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T16:58:54.337-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:00:29.008-0500] {processor.py:186} INFO - Started process (PID=6073) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:00:29.009-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:00:29.011-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:00:29.010-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:00:29.031-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:00:29.027-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:00:29.032-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:00:29.032-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:00:29.033-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:00:29.046-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:02:03.665-0500] {processor.py:186} INFO - Started process (PID=6144) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:02:03.666-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:02:03.669-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:02:03.668-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:02:03.688-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:02:03.684-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:02:03.690-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:02:03.689-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:02:03.691-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:02:03.703-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:03:42.327-0500] {processor.py:186} INFO - Started process (PID=6216) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:03:42.328-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:03:42.330-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:03:42.329-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:03:42.350-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:03:42.346-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:03:42.352-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:03:42.351-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:03:42.353-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:03:42.366-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T17:05:12.602-0500] {processor.py:186} INFO - Started process (PID=6285) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:05:12.603-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:05:12.605-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:05:12.604-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:05:12.624-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:05:12.620-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:05:12.626-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:05:12.625-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:05:12.627-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:05:12.639-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-04-01T17:06:55.697-0500] {processor.py:186} INFO - Started process (PID=6360) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:06:55.698-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:06:55.701-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:06:55.700-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:06:55.720-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:06:55.716-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:06:55.722-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:06:55.721-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:06:55.722-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:06:55.735-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:08:29.741-0500] {processor.py:186} INFO - Started process (PID=6432) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:08:29.742-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:08:29.744-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:08:29.743-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:08:29.764-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:08:29.759-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:08:29.765-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:08:29.764-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:08:29.766-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:08:29.779-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:10:11.886-0500] {processor.py:186} INFO - Started process (PID=6504) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:10:11.887-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:10:11.889-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:10:11.888-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:10:11.908-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:10:11.904-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:10:11.910-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:10:11.909-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:10:11.911-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:10:11.924-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:11:56.721-0500] {processor.py:186} INFO - Started process (PID=6579) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:11:56.722-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:11:56.724-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:11:56.723-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:11:56.744-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:11:56.740-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:11:56.745-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:11:56.745-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:11:56.746-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:11:56.759-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:13:31.422-0500] {processor.py:186} INFO - Started process (PID=6652) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:13:31.423-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:13:31.425-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:13:31.424-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:13:31.445-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:13:31.441-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:13:31.447-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:13:31.446-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:13:31.447-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:13:31.460-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:15:05.182-0500] {processor.py:186} INFO - Started process (PID=6723) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:15:05.183-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:15:05.185-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:15:05.185-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:15:05.205-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:15:05.201-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:15:05.207-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:15:05.206-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:15:05.208-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:15:05.221-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T17:16:39.983-0500] {processor.py:186} INFO - Started process (PID=6794) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:16:39.984-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:16:39.986-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:16:39.985-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:16:40.005-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:16:40.001-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:16:40.007-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:16:40.006-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:16:40.008-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:16:40.021-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:18:15.255-0500] {processor.py:186} INFO - Started process (PID=6868) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:18:15.257-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:18:15.259-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:18:15.259-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:18:15.280-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:18:15.275-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:18:15.281-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:18:15.280-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:18:15.282-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:18:15.296-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-04-01T17:19:58.164-0500] {processor.py:186} INFO - Started process (PID=6943) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:19:58.165-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:19:58.167-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:19:58.167-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:19:58.187-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:19:58.183-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:19:58.189-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:19:58.188-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:19:58.190-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:19:58.203-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:21:42.090-0500] {processor.py:186} INFO - Started process (PID=7017) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:21:42.091-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:21:42.094-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:21:42.093-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:21:42.114-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:21:42.109-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:21:42.115-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:21:42.114-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:21:42.116-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:21:42.130-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-04-01T17:23:19.086-0500] {processor.py:186} INFO - Started process (PID=7088) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:23:19.087-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:23:19.089-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:23:19.089-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:23:19.109-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:23:19.105-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:23:19.111-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:23:19.110-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:23:19.112-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:23:19.124-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:24:55.780-0500] {processor.py:186} INFO - Started process (PID=7160) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:24:55.781-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:24:55.783-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:24:55.782-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:24:55.803-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:24:55.798-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:24:55.804-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:24:55.803-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:24:55.805-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:24:55.818-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:26:28.607-0500] {processor.py:186} INFO - Started process (PID=7230) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:26:28.608-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:26:28.611-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:26:28.610-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:26:28.630-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:26:28.626-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:26:28.632-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:26:28.631-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:26:28.633-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:26:28.645-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-04-01T17:28:04.886-0500] {processor.py:186} INFO - Started process (PID=7302) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:28:04.888-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:28:04.890-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:28:04.889-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:28:04.910-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:28:04.906-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:28:04.911-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:28:04.911-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:28:04.912-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:28:04.925-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-04-01T17:29:33.671-0500] {processor.py:186} INFO - Started process (PID=7369) to work on /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:29:33.672-0500] {processor.py:914} INFO - Processing file /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-01T17:29:33.674-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:29:33.674-0500] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:29:33.695-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:29:33.690-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-01T17:29:33.696-0500] {logging_mixin.py:190} INFO - [2025-04-01T17:29:33.695-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-01T17:29:33.697-0500] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-01T17:29:33.763-0500] {processor.py:208} INFO - Processing /mnt/d/Universidad/ETL/Proyecto_airflow/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
